<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-30
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->setLanguageDir('/modules/core/languages')->_('permalink.config.title'));
?>

<div id="corePermalinkConfigForm" data-dojo-type="dijit.form.Form" data-dojo-props="region: 'center', action: '', method: 'POST', class: 'appForm'">
	<div id="corePermalinkConfigContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="gutters: false, style: 'height: 100%; padding: 0; width: 100%', class: 'appBorderContainer'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
			<button id="corePermalinkConfigSaveButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appSaveIcon'">
				<?php echo $this->translator()->_('global._share.saveAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				require([
					"dojo/_base/lang",
					"dojo/_base/xhr",
					"dojo/dom-form",
					"dojo/topic",
					"dijit/registry"
				], function(dojoLang, dojoXhr, dojoDomForm, dojoTopic) {
					dijit.registry.byId("corePermalinkConfigStandby").show();
					dojoXhr.post({
						url: "<?php echo $this->url(array(), 'core_permalink_config'); ?>",
						content: dojoLang.mixin(dojoDomForm.toObject("corePermalinkConfigForm"), { format: "json" }),
						handleAs: "json",
						load: function(data) {
							dijit.registry.byId("corePermalinkConfigStandby").hide();
							dojoTopic.publish("/app/global/notification", {
								message: ("APP_RESULT_OK" == data.result) ? "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('permalink.config.success'); ?>" : "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('permalink.config.error'); ?>",
								type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
							});
						}
					});
				});
				</script>
			</button>
			
			<button id="corePermalinkConfigResetButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
				<?php echo $this->translator()->_('global._share.resetAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				require([
					"dojo/query",
					"dijit/registry"
				], function() {
					dojo.query(".corePermalinkConfigDefaultLink", "corePermalinkConfigContainer").forEach(function(node) {
						var checkbox = dijit.registry.byNode(node);
						if (checkbox) {
							checkbox.set("checked", true);
						}
					});
				});
				</script>
			</button>
		</div>
		<!-- /Toolbar -->
		
		<!-- Permalinks -->
		<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
				<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('permalink.config.help'); ?>
			</div>
			
			<?php if (count($this->permalinkModules) > 0) : ?>
			<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="region: 'center', closable: true, nested: true, class: 'appContentPane'">
				<?php foreach ($this->permalinkModules as $module => $links) : ?>
				<div id="corePermalinkConfigModulePane_<?php echo $module; ?>" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'center', style: 'margin-top: 8px', title: '<?php echo $this->extensionTranslator()->translateTitle(new Core_Models_Module(array('name' => $module))); ?>'">
					<?php foreach ($links as $index => $link) : ?>
					<div style="padding-bottom: 8px" class="corePermalinkConfigSection">
						<h2 class="appHeadline" style="margin-top: 0"><span><?php echo $link['description']; ?></span></h2>
					
						<!-- Parameters -->
						<div class="appFormRow">
							<label for="params"><?php echo $this->translator()->_('permalink.config.params'); ?>:</label>
							<?php foreach ($link['params'] as $name => $props) : ?><?php echo $name; ?><?php if ($props['required']) : ?><sup>*</sup><?php endif; ?>, <?php endforeach; ?>
						</div>
						<!-- /Parameters -->
					
						<!-- DefaultUrl -->
						<div class="appFormRow">
							<label for="type"><?php echo $this->translator()->_('permalink.config.defaultUrl'); ?>:</label>
							<input id="corePermalinkConfigDefaultButton_<?php echo $module; ?>_<?php echo $link['route']; ?>_<?php echo md5($link['default']); ?>" data-dojo-type="dijit.form.RadioButton" data-dojo-props="class: 'corePermalinkConfigDefaultLink', value: 'default', name: 'type[<?php echo $link['route']; ?>]', checked: <?php if (!isset($this->currLinks[$link['route']]) || (isset($this->currLinks[$link['route']]) && $this->currLinks[$link['route']]['url'] == $link['default'])) : ?>true<?php else : ?>false<?php endif; ?>" />
							<input id="corePermalinkConfigDefaultTextBox_<?php echo $module; ?>_<?php echo $link['route']; ?>_<?php echo md5($link['default']); ?>" data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', name: 'url[<?php echo $link['route']; ?>][]', value: '<?php echo addslashes($link['default']); ?>', style: 'width: 500px', readOnly: true, disabled: <?php if (!isset($this->currLinks[$link['route']]) || (isset($this->currLinks[$link['route']]) && $this->currLinks[$link['route']]['url'] == $link['default'])) : ?>false<?php else : ?>true<?php endif; ?>" />
						</div>
						<!-- /DefaultUrl -->
						
						<!-- PredefinedUrls -->
						<?php if (isset($link['predefined']) && count($link['predefined']) > 0) : ?>
						<div class="appFormRow">
							<label><?php echo $this->translator()->_('permalink.config.predefinedUrls'); ?>:</label>
						</div>
						
						<?php foreach ($link['predefined'] as $url) : ?>
						<div class="appFormRow">
							<label for="type">&nbsp;</label>
							<input id="corePermalinkConfigPredefinedButton_<?php echo $module; ?>_<?php echo $link['route']; ?>_<?php echo md5($url); ?>" data-dojo-type="dijit.form.RadioButton" data-dojo-props="value: 'predefined', name: 'type[<?php echo $link['route']; ?>]', checked: <?php if (isset($this->currLinks[$link['route']]) && $this->currLinks[$link['route']]['url'] == $url) : ?>true<?php else : ?>false<?php endif; ?>" />
							<input id="corePermalinkConfigPredefinedTextBox_<?php echo $module; ?>_<?php echo $link['route']; ?>_<?php echo md5($url); ?>" data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', name: 'url[<?php echo $link['route']; ?>][]', value: '<?php echo addslashes($url); ?>', style: 'width: 500px', readOnly: true, disabled: <?php if (isset($this->currLinks[$link['route']]) && $this->currLinks[$link['route']]['url'] == $url) : ?>false<?php else : ?>true<?php endif; ?>" />
						</div>
						<?php endforeach; ?>
						<?php endif; ?>
						<!-- /PredefinedUrls -->
						
						<!-- CustomUrl -->
						<div class="appFormRow">
							<label for="type"><?php echo $this->translator()->_('permalink.config.customUrl'); ?>:</label>
							<input id="corePermalinkConfigCustomButton_<?php echo $module; ?>_<?php echo $link['route']; ?>" data-dojo-type="dijit.form.RadioButton" data-dojo-props="value: 'custom', name: 'type[<?php echo $link['route']; ?>]', checked: <?php if (isset($this->currLinks[$link['route']]) && 'custom' == $this->currLinks[$link['route']]['type']) : ?>true<?php else : ?>false<?php endif; ?>" />
							<input id="corePermalinkConfigCustomTextBox_<?php echo $module; ?>_<?php echo $link['route']; ?>" data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', name: 'url[<?php echo $link['route']; ?>][]', <?php if (isset($this->currLinks[$link['route']]) && 'custom' == $this->currLinks[$link['route']]['type']) : ?>value: '<?php echo addslashes($this->currLinks[$link['route']]['url']); ?>', disabled: false<?php else : ?>value: '', disabled: true<?php endif; ?>, style: 'width: 500px'" />
							
							<input type="hidden" name="routes[]" value="<?php echo $link['route']; ?>" />
						</div>
						<!-- /CustomUrl -->
					</div>
					<?php endforeach; ?>
				</div>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
		</div>
		<!-- /Permalinks -->
	</div>
</div>

<div id="corePermalinkConfigStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'corePermalinkConfigContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('permalink.config.title'); ?>";

require([
	"dojo/on",
	"dojo/ready",
	"dojo/topic",
	"dojo/NodeList-traverse",
	"dojo/query",
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/RadioButton",
	"dijit/form/TextBox",
	"dijit/layout/BorderContainer",
	"dijit/layout/TabContainer",
	"dijit/registry",
	"dijit/Toolbar",
	"dojox/layout/ContentPane",
	"dojox/widget/Standby"
], function(dojoOn, dojoReady, dojoTopic) {
	dojoReady(function() {
		var handler = dojoTopic.subscribe("/app/global/onLoadComplete/core_permalink_config", function() {
			dojo.query(".dijitRadio", "corePermalinkConfigForm").forEach(function(node) {
				var radio = dijit.registry.byNode(node);
				if (radio) {
					dojoOn(radio, "click", function() {
						// Disable all text boxes
						var section = dojo.query(radio.domNode).closest(".corePermalinkConfigSection")[0];
						dojo.query(".dijitTextBox", section).forEach(function(textbox) {
							dijit.registry.byNode(textbox).set("disabled", true);
						});

						// Enable the text box associating with the radio button
						var formRow = dojo.query(radio.domNode).closest(".appFormRow")[0];
						dojo.query(".dijitTextBox", formRow).forEach(function(textbox) {
							dijit.registry.byNode(textbox).set("disabled", false);
						});
					});
				}
			});
			
			handler.remove();
		});
	});
});
</script>
