<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-27
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('rule.role.title'));
?>

<div id="coreRuleRoleForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
	<div id="coreRuleRoleContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; width: 100%'">
		<!-- Toolbar -->
		<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
			<button id="coreRuleRoleSaveButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', iconClass: 'appIcon appSaveIcon'">
				<?php echo $this->translator()->_('global._share.saveAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				var that = this;
				require([
					"dojo/_base/xhr",
					"dojo/dom-form",
					"dojo/topic",
					"dijit/registry"
				], function(dojoXhr, dojoDomForm, dojoTopic) {
					dijit.registry.byId("coreRuleRoleStandby").show();
					dojoTopic.publish("/app/global/notification", {
						message: "<?php echo $this->translator()->_('global._share.savingAction'); ?>",
						type: "message"
					});
		
					that.set("disabled", true);
					dojoXhr.post({
						url: "<?php echo $this->url(array(), 'core_rule_role'); ?>",
						content: dojoDomForm.toObject("coreRuleRoleForm"),
						handleAs: "json",
						load: function(data) {
							that.set("disabled", false);
							dijit.registry.byId("coreRuleRoleStandby").hide();
							dojoTopic.publish("/app/core/rule/role/onComplete", data);
						}
					});
				});
				</script>
			</button>
			
			<button id="coreRuleRoleCancelButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
				<?php echo $this->translator()->_('global._share.cancelAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				require(["dojo/topic"], function(dojoTopic) {
					dojoTopic.publish("/app/core/rule/role/onCancel");
				});
				</script>
			</button>
		</div>
		<!-- /Toolbar -->
		
		<!-- PermissionForm -->
		<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
			<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
				<h2 class="appHeadline" style="margin-top: 0">
					<span><?php echo $this->translator()->_('rule.role.title'); ?></span>
				</h2>
				
				<?php if (!$this->role) : ?>
					<?php echo $this->translator()->_('rule.role.notFound'); ?>
				<?php elseif ($this->role->isRootRole()) : ?>
					<?php echo $this->translator()->_('rule.role.cannotSetRootRole'); ?>
				<?php elseif ($this->role->locked) : ?>
					<?php echo $this->translator()->_('rule.role.cannotSetLockedRole'); ?>
				<?php else : ?>
					<?php echo sprintf($this->translator()->_('rule.role.settingHelp'), $this->role->description); ?>
				<?php endif; ?>	
			</div>
	
			<?php if ($this->role && !$this->role->isRootRole() && !$this->role->locked) : ?>			
			<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="region: 'center', closable: true, nested: true, class: 'appContentPane'">
				<?php foreach ($this->modules as $index => $module) : ?>
				<div id="coreRuleRoleModulesPane_<?php echo $module->name; ?>" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="title: '<?php echo $this->extensionTranslator()->translateTitle($module); ?>', href: '<?php echo $this->url(array(), 'core_rule_role'); ?>?format=html&role_id=<?php echo $this->role->role_id; ?>&mod=<?php echo $module->name; ?>', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>', style: 'margin-top: 8px'">
				</div>
				<?php endforeach; ?>
			</div>
			<?php endif; ?>
		</div>
		<!-- /PermissionForm -->
		
		<input type="hidden" name="format" value="json" />
		<input type="hidden" name="role_id" value="<?php echo $this->role->role_id; ?>" />
	</div>
</div>

<div id="coreRuleRoleStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'coreRuleRoleContainer', imageText: '<?php echo $this->translator(true)->_('global._share.loadingAction'); ?>'"></div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/layout/TabContainer",
	"dijit/Toolbar",
	"dojox/layout/ContentPane",
	"dojox/widget/Standby"
]);
</script>
