<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('openid.delete.title'));
?>

<?php if ($this->invalidUrl) : ?>
	<div><?php echo sprintf($this->translator()->_('openid.delete.notFound'), $this->url); ?></div>
<?php else : ?>
	<div>
		<?php echo sprintf($this->translator()->_('openid.delete.confirm'), $this->url); ?>
	</div>
	
	<div class="dijitDialogPaneActionBar">
		<!-- YesButton -->
		<button id="coreOpenIdDeleteYesButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.yesMessage'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/_base/xhr",
				"dojo/topic"
			], function(dojoXhr, dojoTopic) {
				dojoXhr.post({
					url: "<?php echo $this->url(array(), 'core_openid_delete'); ?>",
					content: {
						openid_url: "<?php echo $this->url; ?>",
						format: "json"
					},
					handleAs: "json",
					load: function(data) {
						dojoTopic.publish("/app/core/openid/delete/onComplete", data);
					}
				});
			});
			</script>
		</button>
		<!-- /YesButton -->
		
		<!-- NoButton -->
		<button id="coreOpenIdDeleteNoButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
			<?php echo $this->translator()->_('global._share.noMessage'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require([
				"dojo/topic"
			], function(dojoTopic) {
				dojoTopic.publish("/app/core/openid/delete/onCancel");
			});
			</script>
		</button>
		<!-- /NoButton -->
	</div>
<?php endif; ?>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button"
]);
</script>
