<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-27
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('hook.list.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/styles.css");	
});
</script>

<div id="coreHookListContainer" class="coreExtensionItemsContainer appContentPane">
	<?php if (!$this->hooks || count($this->hooks) == 0) : ?>
		<?php echo $this->translator()->_('hook.list.notFound'); ?>
	<?php else : ?>

	<?php foreach ($this->hooks as $hook) : ?>
	<div class="coreExtensionItem">
		<div class="coreExtensionItemThumbnail">
			<img src="<?php echo $hook->thumbnail; ?>" />
		</div>
		
		<div class="coreExtensionItemDescription">
			<h3><?php echo $this->extensionTranslator()->translateTitle($hook); ?></h3>
			<div style="padding-bottom: 8px"><?php echo $this->extensionTranslator()->translateDescription($hook); ?></div>
			
			<!-- InstallButton -->
			<button id="coreHookListInstallButton_<?php echo $hook->module; ?>_<?php echo $hook->name; ?>" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', disabled: <?php if ((!$this->accessor()->route('core_hook_install') && !$hook->is_installed) || (!$this->accessor()->route('core_hook_uninstall') && $hook->is_installed)) : ?>true<?php else : ?>false<?php endif; ?>, appHookModule: '<?php echo $hook->module; ?>', appHookName: '<?php echo $hook->name; ?>', appIsHookInstalled: <?php if ($hook->is_installed) : ?>true<?php else : ?>false<?php endif; ?>">
				<?php echo $hook->is_installed ? $this->translator()->_('global._share.uninstallAction') : $this->translator()->_('global._share.installAction'); ?>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				var that = this;
				require([
					"dojo/_base/xhr",
					"dojo/topic",
					"dojox/string/sprintf"
				], function(dojoXhr, dojoTopic) {
					that.set("disabled", true);
					var isInstalled = that.get("appIsHookInstalled");
					var module		= that.get("appHookModule");
					var name		= that.get("appHookName");
					dojoXhr.post({
						url: isInstalled ? "<?php echo $this->url(array(), 'core_hook_uninstall'); ?>" : "<?php echo $this->url(array(), 'core_hook_install'); ?>",
						content: {
							mod: module,
							name: name
						},
						handleAs: "json",
						load: function(data) {
							var message = ("APP_RESULT_OK" == data.result)
										? (isInstalled ? "<?php echo $this->translator()->_('hook.uninstall.success'); ?>" : "<?php echo $this->translator()->_('hook.install.success'); ?>") 
										: (isInstalled ? "<?php echo $this->translator()->_('hook.uninstall.error'); ?>" : "<?php echo $this->translator()->_('hook.install.error'); ?>");
							dojoTopic.publish("/app/global/notification", {
								message: dojox.string.sprintf(message, name),
								type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
							});
							that.set("disabled", false);
							if ("APP_RESULT_OK" == data.result) {
								that.set("appIsHookInstalled", !isInstalled);
								that.set("label", isInstalled ? "<?php echo $this->translator()->_('global._share.installAction'); ?>" : "<?php echo $this->translator()->_('global._share.uninstallAction'); ?>");
								dojoTopic.publish("/app/core/hook/" + (isInstalled ? "uninstall" : "install") + "/" + module + "_" + name, {
									module: module,
									name: name
								});
	
								// Reload the current page
								window.location.reload();
							}
						}
					});
				});
				</script>
			</button>
			<!-- /InstallButton -->
			
			<!-- ConfigButton -->
			<?php if ($hook->options !== null) : ?>
			<button id="coreHookListConfigureButton_<?php echo $hook->module; ?>_<?php echo $hook->name; ?>" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', disabled: <?php if (!$hook->is_installed || !$this->accessor()->route('core_hook_config')) : ?>true<?php else : ?>false<?php endif; ?>, appHookConfigAllowed: <?php if ($this->accessor()->route('core_hook_config')) : ?>true<?php else : ?>false<?php endif; ?>, appHookModule: '<?php echo $hook->module; ?>', appHookName: '<?php echo $hook->name; ?>'">
				<?php echo $this->translator()->_('global._share.configureAction'); ?>
				<script type="dojo/on">
				var that = this;
				require(["dojo/topic"], function(dojoTopic) {
					dojoTopic.subscribe("/app/core/hook/install/" + that.get("appHookModule") + "_" + that.get("appHookName"), function(data) {
						that.set("disabled", !that.get("appHookConfigAllowed"));
					});
					dojoTopic.subscribe("/app/core/hook/uninstall/" + that.get("appHookModule") + "_" + that.get("appHookName"), function(data) {
						that.set("disabled", true);
					});
				});
				</script>
				<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
				var that = this;
				require(["dojo/topic"], function(dojoTopic) {
					dojoTopic.publish("/app/core/hook/config/onLoadForm", {
						mod: that.get("appHookModule"),
						name: that.get("appHookName")
					});
				});
				</script>
			</button>
			<?php endif; ?>
			<!-- /ConfigButton -->
		</div>
		
		<div style="clear: both"></div>
	</div>
	<?php endforeach; ?>
	
	<?php endif; ?>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dojox/widget/DialogSimple"
]);
</script>
