<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		message
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-27
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<!-- PrivateMessagesMenuItem -->
<div id="messageUnreadMessagesMenuItem" data-dojo-type="dijit.MenuItem" data-dojo-props="iconClass: 'appIcon appMessageIcon'">
	<a href="<?php echo $this->url(array(), 'message_message_list'); ?>" class="appTopMenuItem" data-app-ajax="true"><?php echo $this->translator()->setLanguageDir('/modules/message/languages')->_('global.layout.message'); ?></a> (<span id="messageUnreadMessagesCounter"><?php echo $this->message()->countUnreadMessages(null); ?></span>)
	<script type="dojo/method">
	var that = this;
	require([
		"dojo/dom-attr",
		"dojo/topic"
	], function(dojoDomAttr, dojoTopic) {
		// Update the number of unread messages:
		// - after marking a message as unread/read
		dojoTopic.subscribe("/app/message/message/mark/onSuccess", function(data) {
			// Don't update the counter if message is deleted
			if ("0" == data.deleted) {
				that._increaseUnreadMessages(("1" == data.unread) ? 1 : -1);
			}
		});
		// - after deleting unread message
		dojoTopic.subscribe("/app/message/message/delete/onSuccess", function(data) {
			if ("0" == data.deleted && "1" == data.unread) {
				that._increaseUnreadMessages(-1);
			}
		});
		that._increaseUnreadMessages = function(increasingNumber) {
			var numUnreadMessages = parseInt(dojoDomAttr.get("messageUnreadMessagesCounter", "innerHTML"));
			numUnreadMessages 	 += increasingNumber;
			if (numUnreadMessages >= 0) {
				dojoDomAttr.set("messageUnreadMessagesCounter", "innerHTML", numUnreadMessages);
			}
		};
	});
	</script>
</div>
<!-- /PrivateMessagesMenuItem -->

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/MenuItem"
]);
</script>
