<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('plugin.config.title'));
?>

<div id="corePluginConfigContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="corePluginConfigSaveButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var self = this;
			require([
				"dojo/_base/xhr",
				"dojo/dom-form",
				"dojo/topic",
				"dojox/string/sprintf"
			], function(dojoXhr, dojoDomForm, dojoTopic) {
				self.set("disabled", true);
				dojoTopic.publish("/app/core/plugin/config/onStart");
				dojoXhr.post({
					url: "<?php echo $this->url(array(), 'core_plugin_config'); ?>",
					content: dojoDomForm.toObject("corePluginConfigForm"),
					handleAs: "json",
					load: function(data) {
						self.set("disabled", false);
						var message = ("APP_RESULT_OK" == data.result) 
									? dojox.string.sprintf("<?php echo $this->translator()->_('plugin.config.success'); ?>", "<?php echo $this->name; ?>") 
									: dojox.string.sprintf("<?php echo $this->translator()->_('plugin.config.error'); ?>", "<?php echo $this->name; ?>");
						dojoTopic.publish("/app/global/notification", {
							message: message,
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					}
				});
			});
			</script>
		</button>
		
		<button id="corePluginConfigCancelButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/core/plugin/config/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- PluginConfigForm -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
			<h2 class="appHeadline" style="margin: 0"><span><?php echo $this->translator()->_('plugin.config.title'); ?></span></h2>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<div id="corePluginConfigForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
				<?php echo $this->configBody; ?>
		
				<input type="hidden" name="mod" value="<?php echo $this->module; ?>" />
				<input type="hidden" name="name" value="<?php echo $this->name; ?>" />
				<input type="hidden" name="format" value="json" />
			</div>
		</div>
	</div>
	<!-- /PluginConfigForm -->
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar"
]);
</script>
