<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-28
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('layout.edit.title'));
?>

<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'sidebar', gutters: false, style: 'height: 100%; padding: 0; width: 100%'">
	<!-- Toolbar -->
	<div data-dojo-type="dijit.Toolbar" data-dojo-props="region: 'top', splitter: false">
		<button id="coreLayoutEditSaveButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'submit', iconClass: 'appIcon appSaveIcon'">
			<?php echo $this->translator()->_('global._share.saveAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			var that = this;
			require([
				"dojo/_base/xhr",
				"dojo/dom-form",
				"dojo/topic"
			], function(dojoXhr, dojoDomForm, dojoTopic) {
				that.set("disabled", true);
				dojoXhr.post({
					url: "<?php echo $this->url(array(), 'core_layout_edit'); ?>",
					content: dojoDomForm.toObject("coreLayoutEditForm"),
					handleAs: "json",
					load: function(data) {
						that.set("disabled", false);
						var message = ("APP_RESULT_OK" == data.result)
									? "<?php echo $this->translator()->_('layout.edit.success'); ?>"
									: "<?php echo $this->translator()->_('layout.edit.error'); ?>";
						dojoTopic.publish("/app/global/notification", {
							message: message,
							type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
						});
					}
				});
			});
			</script>
		</button>
		
		<button id="coreLayoutEditCancelButton" data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', iconClass: 'appIcon appCancelIcon'">
			<?php echo $this->translator()->_('global._share.cancelAction'); ?>
			<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
			require(["dojo/topic"], function(dojoTopic) {
				dojoTopic.publish("/app/core/layout/edit/onCancel");
			});
			</script>
		</button>
	</div>
	<!-- /Toolbar -->
	
	<!-- EditLayoutForm -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', design: 'sidebar', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', class: 'appContentPane'">
			<?php echo sprintf($this->translator()->_('layout.edit.help'), $this->layout, $this->template); ?>
		</div>
		
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center', class: 'appContentPane'">
			<div id="coreLayoutEditForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
				<textarea id="coreLayoutEditContentTextarea" data-dojo-type="dijit.form.SimpleTextarea" data-dojo-props="name: 'content', region: 'center', style: 'height: 100%; width: 100%'"><?php echo $this->content; ?></textarea>
				
				<input type="hidden" name="format" value="json" />
				<input type="hidden" name="template" value="<?php echo $this->template; ?>" />
				<input type="hidden" name="layout" value="<?php echo $this->layout; ?>" />
			</div>
		</div>
	</div>
	<!-- /EditLayoutForm -->
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/form/Button",
	"dijit/form/Form",
	"dijit/form/SimpleTextarea",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/Toolbar"
]);
</script>
