<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-26
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php
$this->headTitle()->set($this->translator()->_('module.list.title'));
?>

<script type="text/javascript">
require(["core/js/base/Resource"], function() {
	core.js.base.Resource.loadCss("<?php echo $this->APP_STATIC_URL; ?>/modules/core/css/admin/default/styles.css");	
});
</script>

<div id="coreModuleListContainer" data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="design: 'headline', gutters: true, style: 'height: 100%; padding: 0; width: 100%'">
	<!-- LeftPane -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'leading', gutters: false, minSize: 200, splitter: true, style: 'height: 100%; padding: 0; width: 20%'">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div class="appTitleBar" style="border-left: none; border-right: none; border-top: none">
				<?php echo $this->translator()->_('module.list.modules'); ?>
			</div>
		</div>
		
		<!-- Modules -->
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'center'">
			<div class="coreExtensionItemsContainer">
				<?php foreach ($this->modules as $module) : ?>
				<div class="coreExtensionItem">
					<div class="coreExtensionItemThumbnail">
						<img src="<?php echo $module->thumbnail; ?>" />
					</div>
					
					<div class="coreExtensionItemDescription">
						<h3><a href="javascript: void(0);" class="coreExtensionItemName" data-app-module="<?php echo $module->name; ?>"><?php if ($moduleTitle = $this->extensionTranslator()->translateTitle($module)) : ?><?php echo $moduleTitle; ?><?php endif; ?></a></h3>
						<div style="padding-bottom: 8px"><?php echo $this->extensionTranslator()->translateDescription($module); ?></div>
						
						<!-- InstallButton -->
						<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button', disabled: <?php if ($module->name == 'core' || (!$this->accessor()->route('core_module_install') && !$module->is_installed) || (!$this->accessor()->route('core_module_uninstall') && $module->is_installed)) : ?>true<?php else : ?>false<?php endif; ?>, appModule: '<?php echo $module->name; ?>', appModuleTitle: '<?php echo addslashes($moduleTitle); ?>', appInstalled: <?php if ($module->is_installed) : ?>true<?php else : ?>false<?php endif; ?>">
							<?php echo $module->is_installed ? $this->translator()->_('global._share.uninstallAction') : $this->translator()->_('global._share.installAction'); ?>
							<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
							var self = this;
							require([
								"dojo/_base/xhr",
								"dojo/dom",
								"dojo/topic",
								"dijit/registry",
								"dojox/string/sprintf"
							], function(dojoXhr, dojoDom, dojoTopic) {
								var isInstalled = self.get("appInstalled");
								var module		= self.get("appModule");
								var moduleTitle = self.get("appModuleTitle");
								if (isInstalled) {
									// Show the confirmation dialog
									dojoDom.byId("coreModuleListUninstallConfirmation").innerHTML = "<?php echo sprintf($this->translator()->_('module.uninstall.confirm'), $moduleTitle); ?>";
									dijit.registry.byId("coreModuleListUninstallModuleDialog").set("appModule", module);
									dijit.registry.byId("coreModuleListUninstallModuleDialog").set("appModuleTitle", moduleTitle);
									dijit.registry.byId("coreModuleListUninstallModuleDialog").show();
								} else {
									// Install the selected module
									self.set("disabled", true);
									dijit.registry.byId("coreModuleListStandby").show();
									dojoXhr.post({
										url: "<?php echo $this->url(array(), 'core_module_install'); ?>",
										content: {
											name: module
										},
										handleAs: "json",
										load: function(data) {
											dijit.registry.byId("coreModuleListStandby").hide();
											var message = ("APP_RESULT_OK" == data.result)
														? "<?php echo $this->translator()->_('module.install.success'); ?>"
														: "<?php echo $this->translator()->_('module.install.error'); ?>";
											dojoTopic.publish("/app/global/notification", {
												message: dojox.string.sprintf(message, moduleTitle),
												type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
											});
											self.set("disabled", false);
											if ("APP_RESULT_OK" == data.result) {
												// Reload the current page
												window.location.reload();
											}
										}
									});
								}
							});
							</script>
						</button>
						<!-- /InstallButton -->
					</div>
					
					<div style="clear: both"></div>
				</div>
				<?php endforeach; ?>
			</div>
			
			<!-- UninstallModuleConfirmationDialog -->
			<div id="coreModuleListUninstallModuleDialog" data-dojo-type="dojox.widget.DialogSimple" data-dojo-props="appModule: null, appModuleTitle: '', title: '<?php echo $this->translator(true)->_('module.uninstall.title'); ?>'">
				<div id="coreModuleListUninstallConfirmation"><?php echo $this->translator()->_('module.uninstall.confirm'); ?></div>
				
				<div class="dijitDialogPaneActionBar">
					<!-- YesButton -->
					<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('global._share.yesMessage'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						var self = this;
						require([
							"dojo/_base/xhr",
							"dojo/dom",
							"dojo/topic",
							"dijit/registry",
							"dojox/string/sprintf"
						], function(dojoXhr, dojoDom, dojoTopic) {
							var module		= dijit.registry.byId("coreModuleListUninstallModuleDialog").get("appModule");
							var moduleTitle = dijit.registry.byId("coreModuleListUninstallModuleDialog").get("appModuleTitle");
							if (!module) {
								return;
							}
							dijit.registry.byId("coreModuleListStandby").show();
							dojoXhr.post({
								url: "<?php echo $this->url(array(), 'core_module_uninstall'); ?>",
								content: {
									name: module
								},
								handleAs: "json",
								load: function(data) {
									dijit.registry.byId("coreModuleListStandby").hide();
									dijit.registry.byId("coreModuleListUninstallModuleDialog").hide();
									var message = ("APP_RESULT_OK" == data.result)
												? "<?php echo $this->translator()->_('module.uninstall.success'); ?>" 
												: "<?php echo $this->translator()->_('module.uninstall.error'); ?>";
									dojoTopic.publish("/app/global/notification", {
										message: dojox.string.sprintf(message, moduleTitle),
										type: ("APP_RESULT_OK" == data.result) ? "message" : "error"
									});
									if ("APP_RESULT_OK" == data.result) {
										// Reload the current page
										window.location.reload();
									}
								}
							});
						});
						</script>
					</button>
					<!-- /YesButton -->
					
					<!-- NoButton -->
					<button data-dojo-type="dijit.form.Button" data-dojo-props="type: 'button'">
						<?php echo $this->translator()->_('global._share.noMessage'); ?>
						<script type="dojo/method" data-dojo-event="onClick" data-dojo-args="e">
						require(["dijit/registry"], function() {
							dijit.registry.byId("coreModuleListUninstallModuleDialog").hide();
						});
						</script>
					</button>
					<!-- /NoButton -->
				</div>
			</div>
			<!-- /UninstallModuleConfirmationDialog -->
		</div>
		<!-- /Modules -->
	</div>
	<!-- /LeftPane -->
	
	<!-- CenterPane -->
	<div data-dojo-type="dijit.layout.BorderContainer" data-dojo-props="region: 'center', gutters: false">
		<div data-dojo-type="dijit.layout.ContentPane" data-dojo-props="region: 'top', splitter: false">
			<div class="appTitleBar" style="border-left: none; border-right: none; border-top: none">
				<?php echo $this->translator()->_('module.list.extensions'); ?>
			</div>
		</div>
		
		<div id="coreModuleListExtenionsPane" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="region: 'center', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>'">
			<div class="appCenter">
				<div><?php echo $this->translator()->_('module.list.extensionsHelp'); ?></div>
			</div>
		</div>
	</div>
	<!-- /CenterPane -->
</div>

<div id="coreModuleListStandby" data-dojo-type="dojox.widget.Standby" data-dojo-props="target: 'coreModuleListContainer'"></div>

<script type="text/javascript">
document.title = "<?php echo $this->translator()->setLanguageDir('/modules/core/languages')->_('module.list.title'); ?>";

require([
	"dojo/_base/lang",
	"dojo/dom-attr",
	"dojo/io-query",
	"dojo/on",
	"dojo/ready",
	"dojo/topic",
	"dojo/NodeList-dom",
	"dojo/NodeList-traverse",
	"dojo/parser",
	"dojo/query",
	"dijit/form/Button",
	"dijit/layout/BorderContainer",
	"dijit/layout/ContentPane",
	"dijit/registry",
	"dojox/layout/ContentPane",
	"dojox/string/sprintf",
	"dojox/widget/DialogSimple",
	"dojox/widget/Standby",
	"core/js/base/views/Helper"
], function(dojoLang, dojoDomAttr, dojoIoQuery, dojoOn, dojoReady, dojoTopic) {
	dojoReady(function() {
		// Load extensions when selecting a module
		dojo.query(".coreExtensionItemName").forEach(function(node, index) {
			dojoOn(node, "click", function() {
				dojo.query(".coreExtensionItem").removeClass("coreExtensionSelectedItem");
				dojo.query(node).closest(".coreExtensionItem").addClass("coreExtensionSelectedItem");
				
				var params = {
					format: "html",
					mod: dojoDomAttr.get(node, "data-app-module")
				};
				dijit.registry.byId("coreModuleListExtenionsPane").set("href", "<?php echo $this->url(array(), 'core_module_list'); ?>" + "?" + dojoIoQuery.objectToQuery(params));
			});
		});

		// Create new helper instance
		var helper = new core.js.base.views.Helper("coreModuleListContainer");
		helper.setModule("core");
		
		// Configure plugin handler
		dojoTopic.subscribe("/app/core/plugin/config/onLoadForm", function(data) {
			var url = "<?php echo $this->url(array(), 'core_plugin_config'); ?>" + "?" + dojoIoQuery.objectToQuery(data);
			helper.showPane(url);
		});
		dojoTopic.subscribe("/app/core/plugin/config/onCancel", dojoLang.hitch(helper, "removePane"));

		// Configure hook handler
		dojoTopic.subscribe("/app/core/hook/config/onLoadForm", function(data) {
			var url = "<?php echo $this->url(array(), 'core_hook_config'); ?>" + "?" + dojoIoQuery.objectToQuery(data);
			helper.showPane(url);
		});
		dojoTopic.subscribe("/app/core/hook/config/onCancel", dojoLang.hitch(helper, "removePane"));
	});		
});
</script>
