<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-24
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<!-- 
DO NOT REMOVE THE ID ATTRIBUTE OF THE FORM. It is used to identify the form in the main layout view script
(/template/admin/layouts/install.phtml)
 -->
<div id="coreInstallCompleteForm" data-dojo-type="dijit.form.Form" data-dojo-props="action: '', method: 'POST', class: 'appForm'">
	<!-- AdminSettings -->
	<h2><?php echo $this->translator()->_('install.complete.admin'); ?></h2>
	
	<div class="appFormRow">
		<label for="prefix"><?php echo $this->translator()->_('install.complete.adminPrefixUrl'); ?>:</label>
		<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', value: 'admin', name: 'prefix', width: '200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('install.complete.adminPrefixUrlRequired'); ?>'" />
	</div>

	<div class="appFormRow">
		<label for="username"><?php echo $this->translator()->_('install.complete.adminUsername'); ?>:</label>
		<input id="coreInstallCompleteUsernameTextBox" data-dojo-type="dijit.form.TextBox" data-dojo-props="type: 'text', value: 'admin', name: 'username', width: '200px', required: true, disabled: true" />
	</div>

	<div class="appFormRow">
		<label for="password"><?php echo $this->translator()->_('install.complete.adminPassword'); ?>:</label>
		<input id="coreInstallCompletePasswordTextbox" data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', value: '<?php echo $this->password; ?>', name: 'password', width: '200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('install.complete.adminPasswordRequired'); ?>', class: 'appLeft'" />
			
		<!-- PasswordStrengthMeter -->
		<div class="appLeft" id="coreInstallCompletePasswordStrengthMeter"></div>
		<!-- /PasswordStrengthMeter -->
		
		<div class="appClear"></div>
	</div>
	
	<div class="appFormRow">
		<label>&nbsp;</label>
		<a href="javascript: void(0);" id="coreInstallCompleteGeneratePassword"><?php echo $this->translator()->_('install.complete.generatePasswordAction'); ?></a>
	</div>

	<div class="appFormRow">
		<label for="email"><?php echo $this->translator()->_('install.complete.adminEmail'); ?>:</label>
		<input data-dojo-type="dijit.form.ValidationTextBox" data-dojo-props="type: 'text', name: 'email', width: '200px', required: true, missingMessage: '<?php echo $this->translator(true)->_('install.complete.adminEmailRequired'); ?>'" />
	</div>
	<!-- /AdminSettings -->
</div>

<script type="text/javascript">
require([
	"dojo/_base/xhr",
	"dojo/dom",
	"dojo/on",
	"dojo/ready",
	"dojo/topic",
	"dojo/parser",
	"dijit/form/Form",
	"dijit/form/TextBox",
	"dijit/form/ValidationTextBox",
	"dijit/registry",
	"core/js/views/PasswordStrengthMeter"
], function(dojoXhr, dojoDom, dojoOn, dojoReady, dojoTopic) {
	dojoReady(function() {
		var handler = dojoTopic.subscribe("/app/global/onLoadComplete/core_install_complete", function() {
			var passwordStrengthMeter = new core.js.views.PasswordStrengthMeter("coreInstallCompletePasswordStrengthMeter");
			passwordStrengthMeter.setUsername(dijit.registry.byId("coreInstallCompleteUsernameTextBox").get("value"));
		
			dojoOn(dijit.registry.byId("coreInstallCompletePasswordTextbox"), "keyup", function() {
				passwordStrengthMeter.checkPassword(dijit.registry.byId("coreInstallCompletePasswordTextbox").get("value"));
			});

			// Generate password handler
			dojoOn(dojoDom.byId("coreInstallCompleteGeneratePassword"), "click", function() {
				dojoXhr.post({
					url: "<?php echo $this->url(array(), 'core_password_generate'); ?>",
					content: {
						hash: false,
						length: 10
					},
					handleAs: "json",
					load: function(data) {
						dijit.registry.byId("coreInstallCompletePasswordTextbox").set("value", data.password);
						passwordStrengthMeter.checkPassword(data.password);
					}
				});
			});
		});
	});
});
</script>
