<?php
/**
 * NextCMS
 * 
 * @author		Nguyen Huu Phuoc <thenextcms@gmail.com>
 * @copyright	Copyright (c) 2011 - 2012, Nguyen Huu Phuoc
 * @license		http://nextcms.org/license.txt	(GNU GPL version 2 or later)
 * @link		http://nextcms.org
 * @category	modules
 * @package		core
 * @subpackage	views
 * @since		1.0
 * @version		2012-07-28
 */

defined('APP_VALID_REQUEST') || die('You cannot access the script directly.');
?>

<?php 
$this->headTitle()->set($this->translator()->_('template.list.title'));
?>

<div data-dojo-type="dijit.layout.TabContainer" data-dojo-props="region: 'center', closable: true, nested: true">
	<div id="coreTemplateListLayoutsPane_<?php echo $this->template; ?>" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('template.list.layouts'); ?>', href: '<?php echo $this->url(array(), 'core_layout_list'); ?>?template=<?php echo $this->template; ?>', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>'">
		<script type="dojo/on" data-dojo-event="downloadend">
		require(["dojo/topic"], function(dojoTopic) {
			dojoTopic.publish("/app/global/onLoadComplete/core_layout_list");
		});
		</script>
	</div>
	
	<div id="coreTemplateListSkinsPane_<?php echo $this->template; ?>" data-dojo-type="dojox.layout.ContentPane" data-dojo-props="title: '<?php echo $this->translator(true)->_('template.list.skins'); ?>', href: '<?php echo $this->url(array(), 'core_skin_list'); ?>?template=<?php echo $this->template; ?>', loadingMessage: '<div class=appCenter><div><span class=dijitContentPaneLoading><?php echo $this->translator(true)->_('global._share.loadingAction'); ?></span></div></div>'">
		<script type="dojo/on" data-dojo-event="downloadend">
		require(["dojo/topic"], function(dojoTopic) {
			dojoTopic.publish("/app/global/onLoadComplete/core_skin_list");
		});
		</script>
	</div>
</div>

<script type="text/javascript">
require([
	"dojo/parser",
	"dijit/layout/TabContainer",
	"dojox/layout/ContentPane"
]);
</script>
